spring.application.name=ai-app-demo1

langchain4j.community.dashscope.chat-model.api-key=sk-ws-H.RXIRDEL.fZzo.MEUCIQCh1hjacQJyH-9vhi6lbiP8FEfvfYCQXbTQ-sASKQ5owQIgNwjgBzxksTljMdb9BhVLQyw06hLFFYJ1DvO021xurnI
langchain4j.community.dashscope.chat-model.model-name=qwen-max
langchain4j.community.dashscope.chat-model.temperature=0.7
langchain4j.community.dashscope.chat-model.max-tokens=8192

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Northwind;encrypt=true;trustServerCertificate=true
spring.datasource.username=readonly
spring.datasource.password=Pass1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

##later to use rag

